### ISSUE TITLE
Crash on drag if subitems array is null instead of empty array

### ISSUE THREAD

**Issue by tkislan** [angular-ui-tree/angular-ui-tree#251]
```
TypeError: Cannot read property 'slice' of null
    at Object.moveTo (file:///<>/angular-ui-tree.js:110:41)
    at dragMove (file:///<>/angular-ui-tree.js:965:32)
    at HTMLDocument.dragMoveEvent (file:///<>/angular-ui-tree.js:1109:15)
    at HTMLDocument.eventHandler (file:///<>/angular.js:2994:21)
```

```
  $scope.list = [
  {
    "id": 1,
    "title": "A",
    "items": [
    {
      "id": 2,
      "title": "B",
    },
    {
      "id": 3,
      "title": "C",
    }
    ]
  }
  ];
```

Info:
Node-Webit 0.10.5
AngularJS v1.3.0-rc.5
Angular UI Tree v2.0.13

**Comment by Voles** [comment]
Closing this issue due to inactivity. See #815 for more information.
Please create a new issue is this still occurs with the current version of the component.
