### ISSUE TITLE
TypeError: Cannot read property 'exp' of undefined

### ISSUE THREAD

**Issue by 18601673727** [angular-ui-tree/angular-ui-tree#295]
```
TypeError: Cannot read property 'exp' of undefined
    at ng.config.$provide.decorator.watchFnToHumanReadableString (<anonymous>:703:19)
    at Scope.ng.config.$provide.decorator.$delegate.__proto__.$watch (<anonymous>:735:28)
    at link (http://localhost:7788/js/dependencies/angular-ui-tree/dist/angular-ui-tree.js:769:17)
    at nodeLinkFn (http://localhost:7788/js/dependencies/angular/angular.js:6737:13)
    at compositeLinkFn (http://localhost:7788/js/dependencies/angular/angular.js:6131:13)
    at nodeLinkFn (http://localhost:7788/js/dependencies/angular/angular.js:6731:24)
    at compositeLinkFn (http://localhost:7788/js/dependencies/angular/angular.js:6131:13)
    at compositeLinkFn (http://localhost:7788/js/dependencies/angular/angular.js:6134:13)
    at compositeLinkFn (http://localhost:7788/js/dependencies/angular/angular.js:6134:13)
    at compositeLinkFn (http://localhost:7788/js/dependencies/angular/angular.js:6134:13) <ol ui-tree-nodes="" ng-model="tree" id="tree-root" class="ng-scope ng-pristine ng-valid angular-ui-tree-nodes">
```

**Comment by miguelbaldi** [comment]
Any plans to really fix that issue?

**Comment by jaredwilli** [comment]
Yes, this is a batarang issue. Thank god, i thought i was going crazy.

**Comment by activedecay** [comment]
AngularJS Inspector suffers from the same issue
