### ISSUE TITLE
Broken http://angular-ui-tree.github.io/website/ 

### ISSUE THREAD

**Issue by sheymann** [angular-ui-tree/angular-ui-tree#335]
Load the project website:

>  Error: [$injector:unpr] http://errors.angularjs.org/1.2.15/$injector/unpr?p0=keysProvider%20%3C-%20keys
    at Error (native)
    at http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:6:450
    at http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:34:510
    at Object.c [as get] (http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:33:83)
    at http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:35:59
    at c (http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:33:83)
    at d (http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:33:300)
    at Object.instantiate (http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:33:464)
    at http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:65:486
    at http://angular-ui-tree.github.io/website/bower_components/angular/angular.min.js:52:156

**Comment by Voles** [comment]
The examples page have been updated, please see http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example
