### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jeni79** [angular-ui-tree/angular-ui-tree#394]
test for function collapseAll and expandAll

RangeError: Maximum call stack size exceeded
    at Object.R (http://localhost:63342/myApp/app/bower_components/angular/angular.min.js)
    at Object.R [as element] (http://localhost:63342/myApp/app/bower_components/angular/angular.min.js:27:150)
    at getRootNodesScope (http://localhost:63342/myApp/app/project/project.js:34:28)
    at l.$scope.expandAll (http://localhost:63342/myApp/app/project/project.js:44:25)
    at l.$scope.expandAll (http://localhost:63342/myApp/app/project/project.js:45:19)
    at l.$scope.expandAll (http://localhost:63342/myApp/app/project/project.js:45:19)
    at l.$scope.expandAll (http://localhost:63342/myApp/app/project/project.js:45:19)
    at l.$scope.expandAll (http://localhost:63342/myApp/app/project/project.js:45:19)
    at l.$scope.expandAll (http://localhost:63342/myApp/app/project/project.js:45:19)
    at l.$scope.expandAll (http://localhost:63342/myApp/app/project/project.js:45:19)

**Comment by twboc** [comment]
same problem here! while dragging an element ajax is triggered and this range error starts to show

`RangeError: Maximum call stack size exceeded
    at Object.toString (native)
    at isDate (http://localhost:9000/bower_components/angular/angular.js:664:19)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1052:18)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1048:18)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1063:16)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1063:16)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1063:16)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1063:16)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1063:16)
    at equals (http://localhost:9000/bower_components/angular/angular.js:1063:16)(anonymous function) @ angular.js:12722(anonymous function) @ angular.js:9490Scope.$digest @ angular.js:16113Scope.$apply @ angular.js:16359done @ angular.js:10791completeRequest @ angular.js:10989requestLoaded @ angular.js:10930
hierarchies.directive.js:289 waiting.....`
