### ISSUE TITLE
Error on drag: this.parent.$nodeScope is null and gives error

### ISSUE THREAD

**Issue by luciano-masuero** [angular-ui-tree/angular-ui-tree#511]
Hi,

First of all. Thanks for this great app

Then, to my issue.

We are trying to use it as is explained at the doc... (Version: 2.6.0)

We have the view:
```html
<!-- Nested node template -->
<script type="text/ng-template" id="nodes_renderer.html">
  <div ui-tree-handle class="tree-node tree-node-content" data-caca="{{node.title}}">
    <a class="btn btn-success btn-xs" ng-if="node.nodes && node.nodes.length > 0" data-nodrag ng-click="toggle(this)"><span
        class="glyphicon"
        ng-class="{
          'glyphicon-chevron-right': collapsed,
          'glyphicon-chevron-down': !collapsed
        }"></span></a>
    {{node.title}}
    <a class="pull-right btn btn-danger btn-xs" data-nodrag ng-click="remove(this)"><span
        class="glyphicon glyphicon-remove"></span></a>
    <a class="pull-right btn btn-primary btn-xs" data-nodrag ng-click="newSubItem(this)" style="margin-right: 8px;"><span
        class="glyphicon glyphicon-plus"></span></a>
  </div>
  <ol ui-tree-nodes="" ng-model="node.nodes" ng-class="{hidden: collapsed}">
    <li ng-repeat="node in node.nodes" ui-tree-node ng-include="'nodes_renderer.html'">
    </li>
  </ol>
</script>

<div class="row">
  <div class="col-sm-12">
    <h3>Basic Example</h3>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div ui-tree id="tree-root">
      <ol ui-tree-nodes ng-model="data">
        <li ng-repeat="node in data" ui-tree-node ng-include="'nodes_renderer.html'"></li>
      </ol>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="info">
      {{info}}
    </div>
    <pre class="code">{{ data | json }}</pre>
  </div>
</div>
```

And on the js we have:
```javascript
$scope.remove = function (scope) {
        scope.remove();
      };

      $scope.toggle = function (scope) {
        scope.toggle();
      };

      $scope.moveLastToTheBeginning = function () {
        var a = $scope.data.pop();
        $scope.data.splice(0, 0, a);
      };

      $scope.newSubItem = function (scope) {
        var nodeData = scope.$modelValue;
        nodeData.nodes.push({
          id: nodeData.id * 10 + nodeData.nodes.length,
          title: nodeData.title + '.' + (nodeData.nodes.length + 1),
          nodes: []
        });
      };

      $scope.collapseAll = function () {
        $scope.$broadcast('collapseAll');
      };

      $scope.expandAll = function () {
        $scope.$broadcast('expandAll');
      };

      $scope.data = [
          {
              id : -1,
              title : 'I am the root',
              nodes : [
                {
                    'id': 1,
                    'title': 'node1',
                    'nodes': [
                      {
                        'id': 11,
                        'title': 'node1.1',
                        'nodes': [
                          {
                            'id': 111,
                            'title': 'node1.1.1',
                            'nodes': []
                          }
                        ]
                      },
                      {
                        'id': 12,
                        'title': 'node1.2',
                        'nodes': []
                      }
                    ]
                  }, {
                    'id': 2,
                    'title': 'node2',
                    'nodes': [
                      {
                        'id': 21,
                        'title': 'node2.1',
                        'nodes': []
                      },
                      {
                        'id': 22,
                        'title': 'node2.2',
                        'nodes': []
                      }
                    ]
                  }, {
                    'id': 3,
                    'title': 'node3',
                    'nodes': [
                      {
                        'id': 31,
                        'title': 'node3.1',
                        'nodes': []
                      }
                    ]
                  }
              ]
          }

      ];
```

Practically the same as on the basic example.

Now, when we click on a rooot node (in this example is **I am the root**) it throws the following error:

```
TypeError: Cannot read property '$id' of null
    at Object.dragInfo.apply (http://127.0.0.1:8080/js/vendor.js:31906:85)
    at http://127.0.0.1:8080/js/vendor.js:31595:30
    at Scope.$get.Scope.$eval (http://127.0.0.1:8080/js/vendor.js:14466:28)
    at Scope.$get.Scope.$apply (http://127.0.0.1:8080/js/vendor.js:14565:23)
    at link.dragEnd (http://127.0.0.1:8080/js/vendor.js:31594:36)
    at HTMLDocument.link.dragEndEvent (http://127.0.0.1:8080/js/vendor.js:31636:15)
    at HTMLDocument.eventHandler (http://127.0.0.1:8080/js/vendor.js:3032:21) undefined
```

I can not tell why is this happening and what are we doin wrong

Just to try I change the line 1205:
```
angular.module('ui.tree')
  dragInfo
    apply
```  

from:
```javascript
if (this.index === this.sourceInfo.index && this.parent.$nodeScope.$id === this.source.$nodeScope.$id) {
```
to:
```javascript
if (this.index === this.sourceInfo.index && this.parent.$nodeScope && this.parent.$nodeScope.$id === this.source.$nodeScope.$id) {
```

and the error does not occurs anymore but guess that is not the solution..

Do you have any clue about what this may be happening?

NOTE: Sorry for my english

Regards,
Luciano

**Comment by Voles** [comment]
This is probably the same issue which is fixed with #510. Can you retest with this fix and confirm? Thanks.

**Comment by ppuleo** [comment]
It looks like PR #510 added the expectation that `parent.$nodeScope` shouldn't be null even when there's no nesting. I might be missing something but shouldn't the expectation be what @luciano-masuero included above? For readability, it might be easier to break it up though:

````javascript
// node was dropped into the same index slot
if (this.index === this.sourceInfo.index) {

  // the parent and source $nodeScopes exist and are the same
  if (this.parent.$nodeScope && this.parent.$nodeScope.$id === this.source.$nodeScope.$id) {
    return; // The node wasn't moved
  }
}
````

**Comment by joechimo** [comment]
Not exactly sure what changed, but  encountered this issue as well.  I took a look and there are two issues here.
1. It looks like we should be looking at this.$parent.$id and not this.parent.$nodeScope.$id
2. An additional problem occur when the root item is an array and not an object.  The condition only looks at the $parentNodeScope of the source, but this will be null if the parent is an array of scope.  The condition needs to handle both scenarios.

I fixed both issues with the following:

```javascript
// node was dropped in the same place - do nothing
if (this.index === this.sourceInfo.index) {
    if ((this.source.$parentNodeScope && (this.parent.$id === this.source.$parentNodeScope.$id)) ||
        (this.source.$parentNodesScope && (this.parent.$id === this.source.$parentNodesScope.$id))) {
        return;
    }
}
```

**Comment by ppuleo** [comment]
@joechimo Excellent, thanks! This resolved the issue for me.

**Comment by luciano-masuero** [comment]
Hi guys, sorry for the delay... The PR #512 make it work for me.

Thanks a lot... Now, just to know, will be this released as a hotfix for 2.6.0 or how do you handle the fixes? 
This is just to avoid pointing the bower to the master branch

Regards,
Luciano

**Comment by Voles** [comment]
@luciano-masuero this fix is not yet present in v2.6.0. I want to release v2.7.0 when #470 is merged.
For now you temporarily have to refer to the `master` branch (I recommend referring to a specific commit).

**Comment by luciano-masuero** [comment]
Thanks a lot

**Comment by nandhinit** [comment]
Uncaught TypeError: Cannot read property '$element' of null
    at dragMove (angular-ui-tree.js:1117)
    at HTMLDocument.dragMoveEvent (angular-ui-tree.js:1280)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3) i am using connection trees .it is working but in console it shows this error.can you  help me to fix the issue?
