### ISSUE TITLE
How to download and open the project

### ISSUE THREAD

**Issue by Rimiki-Romio** [angular-ui-tree/angular-ui-tree#632]
Dears I liked the project and I would like to work on it but didn't know how to open and work on the project. Thank you for any help and steps!

**Comment by StefanCodes** [comment]
This section has the details you need: https://github.com/angular-ui-tree/angular-ui-tree#useful-commands

What you basically need to do:
* Install Gulp and Bower on your machine
* From your source directory, run `bower install` to install third party dependencies
* Run `gulp build` to compile the source (this will build the files in ./dist)
* Run `gulp serve` if you want to run the demo site locally and test your changes
(If you're running in Windows, make sure your command window runs as administrator when you run `gulp serve` due to some symlink issues)

**Comment by Ramy-Rzem** [comment]
Thank you for your answer. 
After doing that and when I try to access to the local server with browser using: http://localhost:9000 I get nothing !

**Comment by StefanCodes** [comment]
What was the output when you ran `gulp serve`?

This was mine (and I could use the site on port 9090):
````
C:\dev\angular-ui-tree>gulp serve
[20:24:55] Using gulpfile C:\dev\angular-ui-tree\gulpfile.js
[20:24:55] Starting 'serve'...
[20:24:55] Starting 'clean:examples'...
[20:24:55] Starting 'scripts:setup'...
[20:24:55] Starting 'styles'...
[20:24:56] Finished 'serve' after 774 ms
[20:24:56] Finished 'clean:examples' after 777 ms
[20:24:56] gulp-symlink:C:\dev\angular-ui-tree\source symlinked to examples/source
[20:24:56] Finished 'scripts:setup' after 784 ms
[20:24:56] Finished 'styles' after 562 ms
[20:24:56] Starting 'connect'...
[20:24:56] Finished 'connect' after 528 ms
[20:24:56] Starting 'watch'...
[20:24:57] Finished 'watch' after 85 ms
[20:24:57] Starting 'open'...
[20:24:57] Finished 'open' after 9.24 ms
[20:24:57] Server started http://localhost:9000
[20:24:57] LiveReload started on port 35729
````

**Comment by Rimiki-Romio** [comment]
This is the output when I run gulp serve:

Your environment has been set up for using Node.js 4.2.1 (x64) and npm.

C:\Users\Ramy-PC\AppData\Roaming\npm\angular-ui-tree-master>cd C:\Users\Ramy-PC\
AppData\Roaming\npm\angular-ui-tree-master\gulpfile.js
The directory name is invalid.

C:\Users\Ramy-PC\AppData\Roaming\npm\angular-ui-tree-master>gulp serve
[07:58:07] Using gulpfile ~\AppData\Roaming\npm\angular-ui-tree-master\gulpfile.
js
[07:58:07] Starting 'serve'...
[07:58:07] Starting 'clean:examples'...
[07:58:07] Starting 'scripts:setup'...
[07:58:07] 'scripts:setup' errored after 40 ms
[07:58:07] AssertionError: missing path
    at Module.require (module.js:364:3)
    at require (module.js:385:17)
    at requireFn (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-ui-tree-master\no
de_modules\gulp-load-plugins\index.js:37:14)
    at Object.defineProperty.get (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-u
i-tree-master\node_modules\gulp-load-plugins\index.js:68:18)
    at Gulp.<anonymous> (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-ui-tree-ma
ster\tasks\scripts.js:7:14)
    at module.exports (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-ui-tree-mast
er\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-
ui-tree-master\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-
ui-tree-master\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-ui-
tree-master\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at Gulp.<anonymous> (C:\Users\Ramy-PC\AppData\Roaming\npm\angular-ui-tree-ma
ster\gulpfile.js:27:15)
[07:58:07] Finished 'serve' after 94 ms
[07:58:07] Finished 'clean:examples' after 106 ms

**Comment by Rimiki-Romio** [comment]
I think I have error that you don't have, I don't know where it come from.

**Comment by Voles** [comment]
I'm not really sure if this issue is caused by Windows, `gulp-load-plugins` or a combination of both.

This issue seems to be similar to yours, have you seen this post before? https://github.com/google/web-starter-kit/issues/655

**Comment by StefanCodes** [comment]
That's an odd error and not one I'd expect to see.
I did a fresh checkout on my machine to see if I could reproduce it and didn't have any problems. Here's the commands I used:
(Lengthy output omitted, but I did receive several errors during `npm install` that were not fatal)

```
C:\t>git clone https://github.com/angular-ui-tree/angular-ui-tree.git
C:\t>cd angular-ui-tree
C:\t\angular-ui-tree>bower install
C:\t\angular-ui-tree>npm install
C:\t\angular-ui-tree>gulp build
C:\t\angular-ui-tree>gulp serve
[21:11:48] Using gulpfile C:\t\angular-ui-tree\gulpfile.js
[21:11:48] Starting 'serve'...
[21:11:48] Starting 'clean:examples'...
[21:11:49] Starting 'scripts:setup'...
[21:11:49] Starting 'styles'...
[21:11:49] Finished 'serve' after 224 ms
[21:11:49] Finished 'clean:examples' after 225 ms
[21:11:49] gulp-symlink:C:\t\angular-ui-tree\source symlinked to examples/source
[21:11:49] Finished 'scripts:setup' after 251 ms
[21:11:49] Finished 'styles' after 182 ms
[21:11:49] Starting 'connect'...
[21:11:49] Finished 'connect' after 124 ms
[21:11:49] Starting 'watch'...
[21:11:49] Finished 'watch' after 60 ms
[21:11:49] Starting 'open'...
[21:11:49] Finished 'open' after 3.93 ms
[21:11:49] Server started http://localhost:9000
[21:11:49] LiveReload started on port 35729
```

**Comment by derek-adair** [comment]
This is almost certainly an issue with how you've installed node.js.  I highly suggest just using [nvm](https://github.com/creationix/nvm).

**Comment by jacobscarter** [comment]
Closing this issue due to inactivity. See #815 for more information.
Please create a new issue is this still occurs with the current version of the component.
