### ISSUE TITLE
Uncaught Error in dragEnd when moving nodes in a "deep" tree structure.

### ISSUE THREAD

**Issue by codephreek** [angular-ui-tree/angular-ui-tree#836]
**Bug**

Uncaught Error in dragEnd when moving nodes in a "deep" tree structure.

Using the basic example here to replicate issue (http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example)

1) Add at least 13 sub nodes to Node 1 by clicking "+"
2) Move node 1.15 under 1.14
3) Move node 1.14 under 1.13
4) Repeat 1.13 under 1.12, 1.12 under 1.11 ... while monitoring console output in a debugger.
5) *Approximately* when moving node 1.6 under 1.5 - the error appears.

**What is the expected behavior?**
Should not occur.  

**What is the motivation / use case for changing the behavior?**
This causes downstream errors where the tree structure is no longer modifiable (can not add, move, delete nodes etc.) 

**Which versions of Angular, UI Tree and which browser / OS are affected by this issue? Did this work in previous versions of Angular, UI Tree? Please also test with the latest version.**
V2.17
Chrome 53.0.2785.116
Win7 64-bit

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
   Error: [$rootScope:infdig] http://errors.angularjs.org/1.5.8/$rootScope/infdig?   p0=10&p1=%5B%5B%7B%7D%2C%7B%22msg%22%3A%22collapsed%22%2C%22newVal%22%3Afalse%7D%2C%7B%7D%2C%7B%22msg%22%3A%22expandOnHover%22%2C%22newVal%22%3Afalse%7D%2C%7B%22msg%22%3A%22scrollContainer%22%2C%22newVal%22%3Anull%7D%2C%7B%22msg%22%3A%22node.nodes%20%26%26%20node.nodes.length%20%3E%200%22%2C%22newVal%22%3Atrue%7D%2C%7B%22msg%22%3A%22fn%3A%20function%20(c%2Ce%2Cf%2Cg)%7Bf%3Dd%26%26g%3Fg%5B0%5D%3Aa(c%2Ce%2Cf%2Cg)%3Breturn%20b(f%2Cc%2Ce)%7D%22%2C%22newVal%22%3A%22node1.11%22%7D%2C%7B%22msg%22%3A%22%7B%5Cn%20%20%20%20%20%20%20%20%20%20'glyphicon-chevron-right'%3A%20colla
....
%3A%22fn%3A%20function%20()%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20attrs.nodropEnabled%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%22%7D%2C%7B%22msg%22%3A%22%7Bhidden%3A%20collapsed%7D%22%2C%22newVal%22%3A%7B%22hidden%22%3Afalse%7D%7D%5D%5D
    at Error (native)
    at http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:6:412
    at m.$digest (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:144:27)
    at m.$apply (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:146:113)
    at dragEnd (http://angular-ui-tree.github.io/angular-ui-tree/source/directives/uiTreeNode.js:660:32)
    at HTMLDocument.dragEndEvent (http://angular-ui-tree.github.io/angular-ui-tree/source/directives/uiTreeNode.js:720:15)
    at Sf (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:37:127)
    at HTMLDocument.d (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:37:74)

**Comment by m1llen1um** [comment]
Example:
[![https://gyazo.com/d0be8d62d421b1f2ceee0015722a4b7e](https://i.gyazo.com/d0be8d62d421b1f2ceee0015722a4b7e.gif)](https://gyazo.com/d0be8d62d421b1f2ceee0015722a4b7e)

**Comment by Voles** [comment]
This is probably due to limitations of Angular (prevent infinite loops). We'll need to look into this.

**Comment by m1llen1um** [comment]
I have a solution. Please check my pull request #841 

you can see here the result:
[![https://gyazo.com/64fe366247ed85a3c3196ccdfa3c3d92](https://i.gyazo.com/64fe366247ed85a3c3196ccdfa3c3d92.gif)](https://gyazo.com/64fe366247ed85a3c3196ccdfa3c3d92)

**Comment by codephreek** [comment]
@m1llen1um  This seems to have improved the depth of the tree, however I am still able to reproduce the error with 20+ levels.

**Comment by m1llen1um** [comment]
@codephreek I'm sorry but I can't reproduce your case. Can you provide me more detailed example? _jsbin.com_ example will be great, since my PR is still under review.

**Comment by codephreek** [comment]
@m1llen1um I apologize, my fault entirely!  I did not update/apply the solution properly.  The solution works magnificently.
