### ISSUE TITLE
ui-tree not working with table tag

### ISSUE THREAD

**Issue by yusuken1983** [angular-ui-tree/angular-ui-tree#982]
An error is output to the console.

http://angular-ui-tree.github.io/angular-ui-tree/#/table-example

```
angular.js:11706 TypeError: Cannot read property 'addClass' of null
    at link (http://angular-ui-tree.github.io/angular-ui-tree/source/directives/uiTree.js:54:34)
    at Z (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:70:149)
    at I (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:59:255)
    at g (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:51:335)
    at g (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:51:352)
    at g (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:51:352)
    at http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:50:444
    at link (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular-route/angular-route.min.js:7:408)
    at Z (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:70:149)
    at I (http://angular-ui-tree.github.io/angular-ui-tree/bower_components/angular/angular.min.js:59:255) <table ui-tree="" id="tree-root" class="table table-responsive angular-ui-tree">
```

**Comment by yusuken1983** [comment]
duplicate of #967
